modLoader="lowcodefml"
loaderVersion="*"
issueTrackerURL="https://github.com/OOrreeooss/MetallicTinkering/issues"
license="MIT"

[[mods]]
    modId="metallictinkering"
    version="1.2.0"
    displayName="Metallic Tinkering"
    logoFile="pack.png"
    authors="OOrreeooss"
    description='''
    Adds various ores & alloys that are compatible with Tinkers' Construct
    '''
    displayURL="https://modrinth.com/mod/metallic-tinkering"

[[dependencies.metallictinkering]]
    modId="tconstruct"
    mandatory=false
    versionRange="[3.11.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.metallictinkering]]
    modId="jsonthings"
    mandatory=true
    versionRange="[0.9.9,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.metallictinkering]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"

